"""Constants and enums for msasim"""

import _Sailfish
from enum import Enum

MODEL_CODES = _Sailfish.modelCode

SITE_RATE_MODELS = _Sailfish.SiteRateModel

class SIMULATION_TYPE(Enum):
    NOSUBS = 0
    DNA = 1
    PROTEIN = 2


SIMULATION_TYPES = set(item for item in SIMULATION_TYPE)


# protein models:
# CPREV45,
# DAYHOFF,
# JONES,	// THIS IS JTT
# AAJC, // amino acid JC
# MTREV24,
# WAG,
# HIVB,
# HIVW,
# LG,
# EX_BURIED, 
# EX_EXPOSED,
# EHO_EXTENDED,
# EHO_HELIX,
# EHO_OTHER,
# EX_EHO_BUR_EXT,
# EX_EHO_BUR_HEL,
# EX_EHO_BUR_OTH,
# EX_EHO_EXP_EXT,
# EX_EHO_EXP_HEL,
# EX_EHO_EXP_OTH

PROTEIN_MODELS = {
    MODEL_CODES.JONES,
    MODEL_CODES.WAG,
    MODEL_CODES.LG,
    MODEL_CODES.MTREV24,
    MODEL_CODES.CPREV45,
    MODEL_CODES.DAYHOFF,
    MODEL_CODES.HIVB,
    MODEL_CODES.HIVW,
    MODEL_CODES.EX_BURIED,
    MODEL_CODES.EX_EXPOSED,
    MODEL_CODES.EHO_EXTENDED,
    MODEL_CODES.EHO_HELIX,
    MODEL_CODES.EHO_OTHER,
    MODEL_CODES.EX_EHO_BUR_EXT,
    MODEL_CODES.EX_EHO_BUR_HEL,
    MODEL_CODES.EX_EHO_BUR_OTH,
    MODEL_CODES.EX_EHO_EXP_EXT,
    MODEL_CODES.EX_EHO_EXP_HEL,
    MODEL_CODES.EX_EHO_EXP_OTH,
    MODEL_CODES.CUSTOM,
    MODEL_CODES.AAJC,
}

# DNA models:
# NUCJC,
# GTR,
# HKY,
# TAMURA92,
# WYANGMODEL,

DNA_MODELS = {
    MODEL_CODES.NUCJC,
    MODEL_CODES.GTR,
    MODEL_CODES.HKY,
    MODEL_CODES.TAMURA92,
    MODEL_CODES.CUSTOM,
}