"""Constants and enums for msasim"""

import _Sailfish

MODEL_CODES = _Sailfish.modelCode
ALPHABET_CODES = _Sailfish.alphabetCode

SITE_RATE_MODELS = _Sailfish.SiteRateModel

ALPHABET_SIZES = {ALPHABET_CODES.DNA: 4, ALPHABET_CODES.PROTEIN: 20, ALPHABET_CODES.CODON: 61}


SIMULATION_TYPES = set([ALPHABET_CODES.DNA, ALPHABET_CODES.PROTEIN, ALPHABET_CODES.CODON])


PROTEIN_MODELS = {
    MODEL_CODES.JONES,
    MODEL_CODES.WAG,
    MODEL_CODES.LG,
    MODEL_CODES.MTREV24,
    MODEL_CODES.CPREV45,
    MODEL_CODES.DAYHOFF,
    MODEL_CODES.HIVB,
    MODEL_CODES.HIVW,
    MODEL_CODES.EX_BURIED,
    MODEL_CODES.EX_EXPOSED,
    MODEL_CODES.EHO_EXTENDED,
    MODEL_CODES.EHO_HELIX,
    MODEL_CODES.EHO_OTHER,
    MODEL_CODES.EX_EHO_BUR_EXT,
    MODEL_CODES.EX_EHO_BUR_HEL,
    MODEL_CODES.EX_EHO_BUR_OTH,
    MODEL_CODES.EX_EHO_EXP_EXT,
    MODEL_CODES.EX_EHO_EXP_HEL,
    MODEL_CODES.EX_EHO_EXP_OTH,
    MODEL_CODES.AAJC,
    MODEL_CODES.REVERSIBLE,
    MODEL_CODES.NONREVERSIBLE,
}

DNA_MODELS = {
    MODEL_CODES.NUCJC,
    MODEL_CODES.GTR,
    MODEL_CODES.HKY,
    MODEL_CODES.TAMURA92,
    MODEL_CODES.REVERSIBLE,
    MODEL_CODES.NONREVERSIBLE,
}

CODON_MODELS = {
    MODEL_CODES.WYANG,
    MODEL_CODES.EMPIRICODON,
    MODEL_CODES.REVERSIBLE,
    MODEL_CODES.NONREVERSIBLE,
}

ALPHABET_MODELS = {
    ALPHABET_CODES.DNA: DNA_MODELS,
    ALPHABET_CODES.PROTEIN: PROTEIN_MODELS,
    ALPHABET_CODES.CODON: CODON_MODELS,
}