"""Constants and enums for msasim"""

import _Sailfish
from enum import Enum

MODEL_CODES = _Sailfish.modelCode
ALPHABET_CODES = _Sailfish.alphabetCode

SITE_RATE_MODELS = _Sailfish.SiteRateModel

class SIMULATION_TYPE(Enum):
    NOSUBS = ALPHABET_CODES.NULLCODE
    DNA = ALPHABET_CODES.NUCLEOTIDE
    PROTEIN = ALPHABET_CODES.AMINOACID
    CODON = ALPHABET_CODES.CODON

ALPHABET_SIZES = {SIMULATION_TYPE.DNA: 4, SIMULATION_TYPE.PROTEIN: 20, SIMULATION_TYPE.CODON: 61}


SIMULATION_TYPES = set(item for item in SIMULATION_TYPE)


PROTEIN_MODELS = {
    MODEL_CODES.JONES,
    MODEL_CODES.WAG,
    MODEL_CODES.LG,
    MODEL_CODES.MTREV24,
    MODEL_CODES.CPREV45,
    MODEL_CODES.DAYHOFF,
    MODEL_CODES.HIVB,
    MODEL_CODES.HIVW,
    MODEL_CODES.EX_BURIED,
    MODEL_CODES.EX_EXPOSED,
    MODEL_CODES.EHO_EXTENDED,
    MODEL_CODES.EHO_HELIX,
    MODEL_CODES.EHO_OTHER,
    MODEL_CODES.EX_EHO_BUR_EXT,
    MODEL_CODES.EX_EHO_BUR_HEL,
    MODEL_CODES.EX_EHO_BUR_OTH,
    MODEL_CODES.EX_EHO_EXP_EXT,
    MODEL_CODES.EX_EHO_EXP_HEL,
    MODEL_CODES.EX_EHO_EXP_OTH,
    MODEL_CODES.AAJC,
    MODEL_CODES.REVERSIBLE,
    MODEL_CODES.NONREVERSIBLE,
}

DNA_MODELS = {
    MODEL_CODES.NUCJC,
    MODEL_CODES.GTR,
    MODEL_CODES.HKY,
    MODEL_CODES.TAMURA92,
    MODEL_CODES.REVERSIBLE,
    MODEL_CODES.NONREVERSIBLE,
}

CODON_MODELS = {
    MODEL_CODES.WYANG,
    MODEL_CODES.EMPIRICODON,
    MODEL_CODES.REVERSIBLE,
    MODEL_CODES.NONREVERSIBLE,
}

ALPHABET_MODELS = {
    SIMULATION_TYPE.DNA: DNA_MODELS,
    SIMULATION_TYPE.PROTEIN: PROTEIN_MODELS,
    SIMULATION_TYPE.CODON: CODON_MODELS,
}