"""
Sailfish simulator
-----------------------

.. currentmodule:: _Sailfish

.. autosummary::
   :toctree: _generate

    DiscreteDistribution
    SimProtocol
    alphabetCode
    modelCode
    modelFactory
    Simulator
    Msa
    Tree
"""

from typing import List, Optional, Dict
from enum import Enum

class DiscreteDistribution:
    def __init__(self, probabilities: List[float]) -> None: ...

class Tree:
    def __init__(self, newick_file: str, is_rooted: bool) -> None:
        """Create Phylogenetic tree object from newick formatted file"""
        ...
    
    @property
    def num_nodes(self) -> int: ...
    
    @property
    def root(self) -> node: ...

class node:
    @property
    def sons(self) -> List[node]: ...
    
    @property
    def num_leaves(self) -> int: ...
    
    @property
    def name(self) -> str: ...
    
    def distance_to_father(self) -> float: ...

class SimProtocol:
    def __init__(self, size: int) -> None: ...
    
    def set_sequence_size(self, size: int) -> None: ...
    def get_sequence_size(self) -> int: ...
    
    def set_insertion_rates(self, rates: List[float]) -> None: ...
    def get_insertion_rate(self, index: int) -> float: ...
    
    def set_deletion_rates(self, rates: List[float]) -> None: ...
    def get_deletion_rate(self, index: int) -> float: ...
    
    def set_insertion_length_distributions(self, distributions: List[DiscreteDistribution]) -> None: ...
    def get_insertion_length_distribution(self, index: int) -> DiscreteDistribution: ...
    
    def set_deletion_length_distributions(self, distributions: List[DiscreteDistribution]) -> None: ...
    def get_deletion_length_distribution(self, index: int) -> DiscreteDistribution: ...
    
    def set_minimum_sequence_size(self, size: int) -> None: ...
    def get_minimum_sequence_size(self) -> int: ...

class sequenceContainer:
    def __init__(self) -> None: ...

class modelCode(Enum):
    NUCJC = ...
    AAJC = ...
    GTR = ...
    HKY = ...
    TAMURA92 = ...
    CPREV45 = ...
    DAYHOFF = ...
    JONES = ...  # THIS IS JTT
    MTREV24 = ...
    WAG = ...
    HIVB = ...
    HIVW = ...
    LG = ...
    EMPIRICODON = ...
    EX_BURIED = ...
    EX_EXPOSED = ...
    EHO_EXTENDED = ...
    EHO_HELIX = ...
    EHO_OTHER = ...
    EX_EHO_BUR_EXT = ...
    EX_EHO_BUR_HEL = ...
    EX_EHO_BUR_OTH = ...
    EX_EHO_EXP_EXT = ...
    EX_EHO_EXP_HEL = ...
    EX_EHO_EXP_OTH = ...
    CUSTOM = ...

class GammaDistribution:
    def __init__(self, alpha: float, categories: int) -> None: ...
    
    def getAllRates(self) -> List[float]: ...
    def getAllRatesProb(self) -> List[float]: ...

class modelFactory:
    def __init__(self) -> None: ...
    
    def set_replacement_model(self, model: modelCode) -> None: ...
    def set_amino_replacement_model_file(self, filepath: str) -> None: ...
    def set_model_parameters(self, parameters: List[float]) -> None: ...
    def setSiteRateModel(
        self,
        rates: List[float],
        stationary_probs: List[float],
        transition_matrix: List[List[float]] = []
    ) -> None: ...
    def reset(self) -> None: ...

class SimulationContext:
    def __init__(self, tree: Tree, seed: int) -> None: ...
    
    def get_tree(self) -> Tree: ...
    def get_nodes_to_save(self) -> List[node]: ...
    def set_save_root(self) -> None: ...
    def set_save_leaves(self) -> None: ...
    def set_save_all_nodes(self) -> None: ...
    def reseed(self, seed: int) -> None: ...


class IndelSimulator:
    def __init__(self, context: SimulationContext, protocol: SimProtocol) -> None: ...
    
    def update_protocol(self, protocol: SimProtocol) -> None: ...
    def generate_events(self) -> None: ...

class AminoSubstitutionSimulator:
    def __init__(self, factory: modelFactory, context: SimulationContext) -> None: ...
    
    def simulate_substitutions(self, length: int) -> sequenceContainer: ...
    def simulate_and_write_substitutions(self, length: int, filepath: str) -> None: ...
    def init_substitution_sim(self) -> None: ...
    def set_save_rates(self, save: bool) -> None: ...
    def clear_rates_vec(self) -> None: ...
    def get_sequence_container(self) -> sequenceContainer: ...
    def set_aligned_sequence_map(self, msa: Msa) -> None: ...
    def get_site_rates(self) -> List[float]: ...

class NucleotideSubstitutionSimulator:
    def __init__(self, factory: modelFactory, context: SimulationContext) -> None: ...
    
    def simulate_substitutions(self, length: int) -> sequenceContainer: ...
    def simulate_and_write_substitutions(self, length: int, filepath: str) -> None: ...
    def init_substitution_sim(self) -> None: ...
    def set_save_rates(self, save: bool) -> None: ...
    def clear_rates_vec(self) -> None: ...
    def get_sequence_container(self) -> sequenceContainer: ...
    def set_aligned_sequence_map(self, msa: Msa) -> None: ...
    def get_site_rates(self) -> List[float]: ...

class Msa:
    def __init__(self, event_dict: Dict, root_node: node, save_list: List[bool]) -> None: ...
    
    def length(self) -> int: ...
    def num_sequences(self) -> int: ...
    def fill_substitutions(self, container: sequenceContainer) -> None: ...
    def print_msa(self) -> None: ...
    def write_msa(self, filepath: str) -> None: ...
    def get_msa_string(self) -> str: ...
    def get_msa(self) -> List[List[str]]: ...