name: Build

on: [push, pull_request]

jobs:
  release_tag:
    runs-on: [ubuntu-latest]
    steps:
    - name: Generate release tag
      id: generate_release_tag
      uses: alexvingg/next-release-tag@v1.0.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      date_tag: ${{ steps.generate_release_tag.outputs.release_tag }}

  build_wheels:
    needs: release_tag
    name: Build wheels on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              os: "ubuntu-latest",
            }
          - {
              os: "windows-latest",
            }
          - {
              os: "macos-14",
            }
          - {
              os: "macos-13",
            }
        # macos-13 is an intel runner, macos-14 is apple silicon

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # - uses: robinraju/release-downloader@v1.9
      #   id: lib-download
      #   with:
      #     repository: "elyawy/Phylolib"
      #     fileName: ${{ matrix.config.lib }}.zip
      #     latest: true
      #     extract: true

      # -  shell: bash
      #    run: |
      #       mkdir libs
      #       mv ./${{ matrix.config.lib }}/build/* ./libs/
      #       tree .

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        with:
          config-file: "pyproject.toml"
 
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.config.os }}
          path: ./wheelhouse/*.whl

  upload_release:
    needs: build_wheels
    steps:
    - name: Get artifacts
      uses: actions/download-artifact@v4
      with:
        name: cibw-wheels-*

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.release_tag.outputs.date_tag }}
        name: Release v${{ needs.release_tag.outputs.date_tag }}
        files: cibw-wheels-*
