name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              os: "ubuntu-latest",
              lib: "Phylolib-24.2-Linux",
            }
        # macos-13 is an intel runner, macos-14 is apple silicon

    steps:
      - uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1.9
        id: lib-download
        with:
          repository: "elyawy/Phylolib"
          fileName: ${{ matrix.config.lib }}.zip
          latest: true
          extract: true

      -  shell: bash
         run: |
            mkdir libs
            mv ./${{ matrix.config.lib }}/build/* ./libs/
            tree .

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: 'cp36-*'
          CIBW_ARCHS: 'auto64'
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
          # config-file: "pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.config.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl